name: ct484_final_project
description: My Study Quiz App project for CT484.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  dotted_border: ^2.0.0
  custom_radio_grouped_button: ^2.0.0
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  provider: ^6.0.5
  logger: ^1.0.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  